/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIpackage;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AhmedTalal
 */
public class Abcense_tables extends javax.swing.JFrame {

    /**
     * Creates new form Abcense_tables
     */
    public Abcense_tables() {
        initComponents();
        this.setLocationRelativeTo(null);
        ShowTime();
        ShowDate();
    }

    void ShowDate(){
       Date d = new Date();
       SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
       Date_Label1.setText(s.format(d));
   }
   void ShowTime(){
       new Timer(0, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               Date d = new Date();
               SimpleDateFormat s = new SimpleDateFormat("hh : mm : ss a");
                Time_Label1.setText(s.format(d));
           }
       }
       ).start();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header_Panel2 = new javax.swing.JPanel();
        ManagerLabel = new javax.swing.JLabel();
        MinusLabel3 = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        ManagerLabel3 = new javax.swing.JLabel();
        Date_Label1 = new javax.swing.JLabel();
        Time_Label1 = new javax.swing.JLabel();
        lectureCombox = new javax.swing.JPanel();
        lectureLabel = new javax.swing.JLabel();
        classLable = new javax.swing.JLabel();
        classCombbox = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        return_button = new javax.swing.JButton();
        lecturcombo = new javax.swing.JComboBox<>();
        weekCombox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header_Panel2.setBackground(new java.awt.Color(22, 160, 133));

        ManagerLabel.setBackground(new java.awt.Color(235, 151, 78));
        ManagerLabel.setFont(new java.awt.Font("Serif", 3, 38)); // NOI18N
        ManagerLabel.setForeground(new java.awt.Color(51, 36, 36));
        ManagerLabel.setText("تطبيق الطالب");

        MinusLabel3.setBackground(new java.awt.Color(235, 151, 78));
        MinusLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MinusLabel3.setForeground(new java.awt.Color(51, 36, 36));
        MinusLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinusLabel3.setText("-");
        MinusLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinusLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinusLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinusLabel3MouseExited(evt);
            }
        });

        CloseLabel.setBackground(new java.awt.Color(235, 151, 78));
        CloseLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CloseLabel.setForeground(new java.awt.Color(51, 36, 36));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("x");
        CloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        ManagerLabel3.setBackground(new java.awt.Color(235, 151, 78));
        ManagerLabel3.setFont(new java.awt.Font("Serif", 3, 38)); // NOI18N
        ManagerLabel3.setForeground(new java.awt.Color(51, 36, 36));
        ManagerLabel3.setText("جدول غياب الطلاب");

        Date_Label1.setBackground(new java.awt.Color(235, 151, 78));
        Date_Label1.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        Date_Label1.setForeground(new java.awt.Color(51, 36, 36));
        Date_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Time_Label1.setBackground(new java.awt.Color(235, 151, 78));
        Time_Label1.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        Time_Label1.setForeground(new java.awt.Color(51, 36, 36));
        Time_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout header_Panel2Layout = new javax.swing.GroupLayout(header_Panel2);
        header_Panel2.setLayout(header_Panel2Layout);
        header_Panel2Layout.setHorizontalGroup(
            header_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_Panel2Layout.createSequentialGroup()
                .addComponent(ManagerLabel)
                .addGap(62, 62, 62)
                .addComponent(Date_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(ManagerLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Time_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(MinusLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_Panel2Layout.setVerticalGroup(
            header_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManagerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addComponent(ManagerLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Date_Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_Panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CloseLabel))
            .addComponent(Time_Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MinusLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lectureCombox.setBackground(new java.awt.Color(4, 75, 76));

        lectureLabel.setFont(new java.awt.Font("Serif", 3, 32)); // NOI18N
        lectureLabel.setForeground(new java.awt.Color(51, 36, 36));
        lectureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lectureLabel.setText("رقم الحصه  :");
        lectureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 100, 37), 2));

        classLable.setFont(new java.awt.Font("Serif", 3, 32)); // NOI18N
        classLable.setForeground(new java.awt.Color(51, 36, 36));
        classLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classLable.setText("الصف:");
        classLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 86, 49), 2));

        classCombbox.setBackground(new java.awt.Color(1, 50, 67));
        classCombbox.setFont(new java.awt.Font("Serif", 3, 25)); // NOI18N
        classCombbox.setForeground(new java.awt.Color(135, 54, 54));
        classCombbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اولي ثانوي", "تانيه ثانوي", "تالته ثانوي" }));
        classCombbox.setSelectedIndex(-1);
        classCombbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 58, 34), 3));
        classCombbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        searchButton.setBackground(new java.awt.Color(51, 110, 123));
        searchButton.setFont(new java.awt.Font("Serif", 3, 32)); // NOI18N
        searchButton.setForeground(new java.awt.Color(51, 36, 36));
        searchButton.setText("البحث");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });

        return_button.setBackground(new java.awt.Color(51, 110, 123));
        return_button.setFont(new java.awt.Font("Serif", 3, 32)); // NOI18N
        return_button.setForeground(new java.awt.Color(51, 36, 36));
        return_button.setText("الرجوع-->>");
        return_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        return_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                return_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                return_buttonMouseExited(evt);
            }
        });

        lecturcombo.setBackground(new java.awt.Color(1, 50, 67));
        lecturcombo.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        lecturcombo.setForeground(new java.awt.Color(135, 54, 54));
        lecturcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "سبت_حد", "اتنين_تلات", "اربع_خميس" }));
        lecturcombo.setSelectedIndex(-1);
        lecturcombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 70, 44), 3));
        lecturcombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        weekCombox.setBackground(new java.awt.Color(1, 50, 67));
        weekCombox.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        weekCombox.setForeground(new java.awt.Color(51, 111, 103));
        weekCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اسبوع1", "اسبوع2", "اسبوع3", "اسبوع4" }));
        weekCombox.setSelectedIndex(-1);
        weekCombox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 67, 42), 3));
        weekCombox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout lectureComboxLayout = new javax.swing.GroupLayout(lectureCombox);
        lectureCombox.setLayout(lectureComboxLayout);
        lectureComboxLayout.setHorizontalGroup(
            lectureComboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lectureComboxLayout.createSequentialGroup()
                .addComponent(classCombbox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(classLable, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lectureComboxLayout.createSequentialGroup()
                .addComponent(weekCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lecturcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(lectureComboxLayout.createSequentialGroup()
                .addGroup(lectureComboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lectureComboxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lectureComboxLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lectureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lectureComboxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        lectureComboxLayout.setVerticalGroup(
            lectureComboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lectureComboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lectureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lectureComboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lecturcombo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(weekCombox))
                .addGap(183, 183, 183)
                .addGroup(lectureComboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classCombbox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 117, 99));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "code", "lecture"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setEnabled(false);
        jTable1.setRowHeight(33);
        jTable1.setRowMargin(5);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lectureCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1298, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header_Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lectureCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinusLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(Login_Frame.ICONIFIED);
    }//GEN-LAST:event_MinusLabel3MouseClicked

    private void MinusLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabel3MouseEntered
        MinusLabel3.setBackground(Color.WHITE);
        MinusLabel3.setOpaque(true);
    }//GEN-LAST:event_MinusLabel3MouseEntered

    private void MinusLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusLabel3MouseExited
        MinusLabel3.setBackground(null);
        MinusLabel3.setOpaque(false);
    }//GEN-LAST:event_MinusLabel3MouseExited

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        CloseLabel.setBackground(Color.RED);
        CloseLabel.setOpaque(true);
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        CloseLabel.setBackground(null);
        CloseLabel.setOpaque(false);
    }//GEN-LAST:event_CloseLabelMouseExited

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
       searchButton.setBackground(Color.DARK_GRAY);
       searchButton.setOpaque(true);
    }//GEN-LAST:event_searchButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        searchButton.setBackground(null);
        searchButton.setOpaque(false);
    }//GEN-LAST:event_searchButtonMouseExited

    private void return_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_buttonMouseEntered
        return_button.setBackground(Color.DARK_GRAY);
        return_button.setOpaque(true);
    }//GEN-LAST:event_return_buttonMouseEntered

    private void return_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_buttonMouseExited
        return_button.setBackground(null);
        return_button.setOpaque(false);
    }//GEN-LAST:event_return_buttonMouseExited

    private void return_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_buttonMouseClicked
        List_Student_Frame lis = new List_Student_Frame();
        this.setVisible(false);
        lis.setVisible(true);
    }//GEN-LAST:event_return_buttonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
       show_level1_list();
    }//GEN-LAST:event_searchButtonMouseClicked

     public Connection getConnection() {
        String unicode = "?useUnicode=yes&characterEncoding=UTF-8";
        String url = "jdbc:mysql://localhost/";
        String db = "teacher";
        Connection conn;
        try {
            conn = DriverManager.getConnection(url + db + unicode, "root", "");
            return conn;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "ERROR", 1);
        }
        return null;
    }
     
     public void show_level1_list()
    {
         String result = "غ";
        try {
            Connection conn = getConnection();
            if(classCombbox.getSelectedItem().equals("اولي ثانوي"))
            {
                if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec1`, `code`,`name` FROM `attendance_level1` WHERE lec1= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec2`, `code`,`name` FROM `attendance_level1` WHERE lec2= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec3`, `code`,`name` FROM `attendance_level1` WHERE lec3= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec4`, `code`,`name` FROM `attendance_level1` WHERE lec4= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec5`, `code`,`name` FROM `attendance_level1` WHERE lec5= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec6`, `code`,`name` FROM `attendance_level1` WHERE lec6= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec7`, `code`,`name` FROM `attendance_level1` WHERE lec7= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec8`, `code`,`name` FROM `attendance_level1` WHERE lec8= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec9`, `code`,`name` FROM `attendance_level1` WHERE lec9= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec10`, `code`,`name` FROM `attendance_level1` WHERE lec10= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec11`, `code`,`name` FROM `attendance_level1` WHERE lec11= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec12`, `code`,`name` FROM `attendance_level1` WHERE lec12= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }
            }else if(classCombbox.getSelectedItem().equals("تانيه ثانوي"))
            {
                if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec1`, `code`,`name` FROM `attendance_level2` WHERE lec1= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec2`, `code`,`name` FROM `attendance_level2` WHERE lec2= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec3`, `code`,`name` FROM `attendance_level2` WHERE lec3= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec4`, `code`,`name` FROM `attendance_level2` WHERE lec4= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec5`, `code`,`name` FROM `attendance_level2` WHERE lec5= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec6`, `code`,`name` FROM `attendance_level2` WHERE lec6= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec7`, `code`,`name` FROM `attendance_level2` WHERE lec7= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec8`, `code`,`name` FROM `attendance_level2` WHERE lec8= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec9`, `code`,`name` FROM `attendance_level2` WHERE lec9= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec10`, `code`,`name` FROM `attendance_level2` WHERE lec10= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec11`, `code`,`name` FROM `attendance_level2` WHERE lec11= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec12`, `code`,`name` FROM `attendance_level2` WHERE lec12= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }
            }else if(classCombbox.getSelectedItem().equals("تالته ثانوي"))
            {
                if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec1`, `code`,`name` FROM `attendance_level3` WHERE lec1= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec2`, `code`,`name` FROM `attendance_level3` WHERE lec2= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع1")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec3`, `code`,`name` FROM `attendance_level3` WHERE lec3= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec4`, `code`,`name` FROM `attendance_level3` WHERE lec4= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec5`, `code`,`name` FROM `attendance_level3` WHERE lec5= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع2")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec6`, `code`,`name` FROM `attendance_level3` WHERE lec6= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec7`, `code`,`name` FROM `attendance_level3` WHERE lec7= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec8`, `code`,`name` FROM `attendance_level3` WHERE lec8= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع3")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec9`, `code`,`name` FROM `attendance_level3` WHERE lec9= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("سبت_حد"))
                {
                    String Query  = "SELECT`lec10`, `code`,`name` FROM `attendance_level3` WHERE lec10= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("اتنين_تلات"))
                {
                    String Query  = "SELECT`lec11`, `code`,`name` FROM `attendance_level3` WHERE lec11= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }else if(weekCombox.getSelectedItem().equals("اسبوع4")& lecturcombo.getSelectedItem().equals("اربع_خميس"))
                {
                    String Query  = "SELECT`lec12`, `code`,`name` FROM `attendance_level3` WHERE lec12= '"+result+"'";
                    PreparedStatement stmt;
                    stmt = conn.prepareStatement(Query);
                    ResultSet re;
                   re = stmt.executeQuery();
                   jTable1.setModel(DbUtils.resultSetToTableModel(re));
                }
            }else
            {
                JOptionPane.showMessageDialog(null, "لم يتم اختيار رقم حصه معين ولا صف دراسي", "ERROR" ,3);
            }
            
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", 1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abcense_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abcense_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abcense_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abcense_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Abcense_tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel Date_Label1;
    private javax.swing.JLabel ManagerLabel;
    private javax.swing.JLabel ManagerLabel3;
    private javax.swing.JLabel MinusLabel3;
    private javax.swing.JLabel Time_Label1;
    private javax.swing.JComboBox<String> classCombbox;
    private javax.swing.JLabel classLable;
    private javax.swing.JPanel header_Panel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> lecturcombo;
    private javax.swing.JPanel lectureCombox;
    private javax.swing.JLabel lectureLabel;
    private javax.swing.JButton return_button;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> weekCombox;
    // End of variables declaration//GEN-END:variables
}
